# This is the default base image for use with user models and workflows.
# It contains a variety of common useful data-science packages and tools.
FROM python:3.8
RUN pip install wandb
COPY ./geo.py /tmp/geo.py
RUN chmod 777 /tmp/geo.py
ENTRYPOINT [ "python","/tmp/geo.py"]